import { Timestamp } from 'firebase/firestore';

export type AssistantType = 'essential' | 'custom';
export type AssistantTone = 'professional' | 'friendly' | 'casual' | 'formal' | 'empathetic' | 'consultative';
export type AssistantStyle = 'formal' | 'conversational' | 'casual';
export type AssistantResponseLength = 'brief' | 'moderate' | 'detailed';
export type DocumentVisibility = 'internal' | 'external' | 'both';

export interface AssistantPersonality {
    tone: AssistantTone;
    style: AssistantStyle;
    responseLength: AssistantResponseLength;
}

export interface AssistantDocumentConfig {
    useAllDocuments: boolean;
    attachedDocumentIds: string[];
    externalDocumentIds: string[];
}

export interface AssistantBehaviorRules {
    responseRules: string[];
    neverSay: string[];
    escalationTriggers: string[];
    openingMessage?: string;
}

export interface Assistant {
    id: string;
    partnerId: string;
    type: AssistantType;
    templateId?: string;

    name: string;
    description: string;
    avatar: string;
    color: string;

    personality: AssistantPersonality;

    documentConfig: AssistantDocumentConfig;

    behaviorRules: AssistantBehaviorRules;

    systemPrompt: string;
    systemPromptAutoGenerated: boolean;
    systemPromptManualOverride?: string;

    allowExternalUse: boolean;

    isActive: boolean;
    temperature: number;
    maxTokens: number;

    createdAt: Timestamp | Date;
    updatedAt: Timestamp | Date;
    createdBy?: string;
    usageCount: number;
}

export interface AssistantTemplate {
    id: string;
    name: string;
    description: string;
    avatar: string;
    color: string;
    category: string;
    personality: AssistantPersonality;
    behaviorRules: Partial<AssistantBehaviorRules>;
    systemPromptTemplate: string;
    suggestedDocumentCategories: string[];
}

export const DEFAULT_ASSISTANT_PERSONALITY: AssistantPersonality = {
    tone: 'professional',
    style: 'conversational',
    responseLength: 'moderate',
};

export const DEFAULT_ASSISTANT_DOCUMENT_CONFIG: AssistantDocumentConfig = {
    useAllDocuments: true,
    attachedDocumentIds: [],
    externalDocumentIds: [],
};

export const DEFAULT_ASSISTANT_BEHAVIOR_RULES: AssistantBehaviorRules = {
    responseRules: [],
    neverSay: [],
    escalationTriggers: [],
    openingMessage: '',
};

export const ASSISTANT_AVATARS: { emoji: string; label: string }[] = [
    { emoji: '🤖', label: 'Robot' },
    { emoji: '🎧', label: 'Support' },
    { emoji: '⚡', label: 'Lightning' },
    { emoji: '✨', label: 'Sparkles' },
    { emoji: '🔧', label: 'Tools' },
    { emoji: '📦', label: 'Package' },
    { emoji: '🎓', label: 'Graduate' },
    { emoji: '👑', label: 'Crown' },
    { emoji: '💬', label: 'Chat' },
    { emoji: '📋', label: 'Clipboard' },
    { emoji: '🎯', label: 'Target' },
    { emoji: '💡', label: 'Idea' },
    { emoji: '🛡️', label: 'Shield' },
    { emoji: '🚀', label: 'Rocket' },
    { emoji: '🌟', label: 'Star' },
];

export const ASSISTANT_COLORS: { value: string; label: string }[] = [
    { value: 'blue', label: 'Blue' },
    { value: 'emerald', label: 'Emerald' },
    { value: 'violet', label: 'Violet' },
    { value: 'amber', label: 'Amber' },
    { value: 'rose', label: 'Rose' },
    { value: 'cyan', label: 'Cyan' },
    { value: 'orange', label: 'Orange' },
    { value: 'indigo', label: 'Indigo' },
];

export const TONE_LABELS: Record<AssistantTone, string> = {
    professional: 'Professional',
    friendly: 'Friendly',
    casual: 'Casual',
    formal: 'Formal',
    empathetic: 'Empathetic',
    consultative: 'Consultative',
};

export const STYLE_LABELS: Record<AssistantStyle, string> = {
    formal: 'Formal',
    conversational: 'Conversational',
    casual: 'Casual',
};

export const LENGTH_LABELS: Record<AssistantResponseLength, string> = {
    brief: 'Brief (1-2 sentences)',
    moderate: 'Moderate (2-3 sentences)',
    detailed: 'Detailed (3-5 sentences)',
};

export const ASSISTANT_TEMPLATES: AssistantTemplate[] = [
    {
        id: 'template-technical-support',
        name: 'Technical Support',
        description: 'Helps customers troubleshoot product issues and provides step-by-step guidance',
        avatar: '🔧',
        color: 'blue',
        category: 'support',
        personality: {
            tone: 'professional',
            style: 'conversational',
            responseLength: 'detailed',
        },
        behaviorRules: {
            responseRules: [
                'Ask for product model or version first',
                'Provide step-by-step instructions',
                'Confirm issue is resolved before closing',
            ],
            neverSay: [
                'I don\'t know',
                'That\'s not my job',
            ],
            escalationTriggers: [
                'Customer mentions legal action',
                'Issue persists after 3 troubleshooting attempts',
            ],
        },
        systemPromptTemplate: 'You are a technical support specialist. Help customers troubleshoot issues with patience and clear step-by-step guidance.',
        suggestedDocumentCategories: ['product', 'faq', 'troubleshooting'],
    },
    {
        id: 'template-order-tracking',
        name: 'Order Tracking',
        description: 'Assists customers with order status, shipping updates, and delivery inquiries',
        avatar: '📦',
        color: 'emerald',
        category: 'support',
        personality: {
            tone: 'friendly',
            style: 'conversational',
            responseLength: 'brief',
        },
        behaviorRules: {
            responseRules: [
                'Ask for order number if not provided',
                'Always provide estimated delivery date',
                'Offer tracking link when available',
            ],
            neverSay: [],
            escalationTriggers: [
                'Order delayed more than 7 days',
                'Customer requests refund',
            ],
        },
        systemPromptTemplate: 'You are an order tracking specialist. Help customers track their orders and provide shipping updates with a friendly tone.',
        suggestedDocumentCategories: ['shipping', 'policies'],
    },
    {
        id: 'template-onboarding',
        name: 'Onboarding Guide',
        description: 'Welcomes new customers and guides them through product setup and features',
        avatar: '🎓',
        color: 'violet',
        category: 'engagement',
        personality: {
            tone: 'friendly',
            style: 'conversational',
            responseLength: 'moderate',
        },
        behaviorRules: {
            responseRules: [
                'Welcome new users warmly',
                'Explain features in simple terms',
                'Offer to schedule a demo call',
            ],
            neverSay: [
                'You should already know this',
            ],
            escalationTriggers: [],
        },
        systemPromptTemplate: 'You are an onboarding specialist. Welcome new customers warmly and guide them through getting started with our product.',
        suggestedDocumentCategories: ['product', 'faq', 'getting-started'],
    },
    {
        id: 'template-vip-concierge',
        name: 'VIP Concierge',
        description: 'Provides white-glove service for premium and high-value customers',
        avatar: '👑',
        color: 'amber',
        category: 'engagement',
        personality: {
            tone: 'formal',
            style: 'formal',
            responseLength: 'detailed',
        },
        behaviorRules: {
            responseRules: [
                'Address customer by name',
                'Offer exclusive benefits proactively',
                'Provide personalized recommendations',
            ],
            neverSay: [
                'Please wait',
                'I\'ll transfer you',
            ],
            escalationTriggers: [
                'Customer expresses dissatisfaction',
            ],
        },
        systemPromptTemplate: 'You are a VIP concierge providing white-glove service. Treat every customer as your most important client with personalized, premium support.',
        suggestedDocumentCategories: ['product', 'pricing', 'policies'],
    },
    {
        id: 'template-appointment',
        name: 'Appointment Scheduler',
        description: 'Helps customers book, reschedule, and manage appointments',
        avatar: '📋',
        color: 'cyan',
        category: 'operations',
        personality: {
            tone: 'professional',
            style: 'conversational',
            responseLength: 'brief',
        },
        behaviorRules: {
            responseRules: [
                'Confirm date, time, and location',
                'Send confirmation details',
                'Offer rescheduling options',
            ],
            neverSay: [],
            escalationTriggers: [
                'No available slots',
            ],
        },
        systemPromptTemplate: 'You are an appointment scheduling assistant. Help customers book and manage their appointments efficiently.',
        suggestedDocumentCategories: ['scheduling', 'policies'],
    },
    {
        id: 'template-product-specialist',
        name: 'Product Specialist',
        description: 'Deep product knowledge expert who answers detailed questions about features and capabilities',
        avatar: '🎯',
        color: 'indigo',
        category: 'sales',
        personality: {
            tone: 'consultative',
            style: 'conversational',
            responseLength: 'detailed',
        },
        behaviorRules: {
            responseRules: [
                'Understand customer needs before recommending',
                'Highlight relevant features',
                'Compare with alternatives when asked',
            ],
            neverSay: [
                'I\'m not sure about that feature',
            ],
            escalationTriggers: [],
        },
        systemPromptTemplate: 'You are a product specialist with deep knowledge of our offerings. Help customers understand features and find the right solution for their needs.',
        suggestedDocumentCategories: ['product', 'pricing', 'faq'],
    },
];

export const ESSENTIAL_ASSISTANT_DEFAULTS: Partial<Assistant>[] = [
    {
        id: 'essential-customer_care',
        type: 'essential',
        name: 'Customer Care',
        description: 'Handles FAQs, support tickets, and account issues',
        avatar: '🎧',
        color: 'blue',
        personality: {
            tone: 'empathetic',
            style: 'conversational',
            responseLength: 'moderate',
        },
        behaviorRules: {
            responseRules: ['Always greet warmly', 'Acknowledge customer concerns'],
            neverSay: ['That\'s not my problem'],
            escalationTriggers: ['Customer requests manager'],
            openingMessage: 'Hello! How can I help you today?',
        },
        systemPrompt: 'You are a customer care specialist. Be empathetic, helpful, and solution-oriented. Always aim to resolve issues on first contact.',
        allowExternalUse: true,
        temperature: 0.7,
        maxTokens: 1024,
    },
    {
        id: 'essential-sales_assistant',
        type: 'essential',
        name: 'Sales Assistant',
        description: 'Provides product info, pricing, and captures leads',
        avatar: '⚡',
        color: 'amber',
        personality: {
            tone: 'friendly',
            style: 'conversational',
            responseLength: 'moderate',
        },
        behaviorRules: {
            responseRules: ['Highlight value propositions', 'Ask qualifying questions'],
            neverSay: ['I don\'t know the price'],
            escalationTriggers: ['Enterprise deal inquiry'],
            openingMessage: 'Hi! Looking for information about our products?',
        },
        systemPrompt: 'You are a sales assistant. Be helpful and informative about products and pricing. Focus on understanding customer needs and matching them with the right solutions.',
        allowExternalUse: true,
        temperature: 0.7,
        maxTokens: 1024,
    },
    {
        id: 'essential-marketing_comms',
        type: 'essential',
        name: 'Marketing Comms',
        description: 'Sends birthday wishes, promotions, and updates',
        avatar: '✨',
        color: 'violet',
        personality: {
            tone: 'friendly',
            style: 'casual',
            responseLength: 'brief',
        },
        behaviorRules: {
            responseRules: ['Keep messages engaging', 'Include clear call-to-action'],
            neverSay: [],
            escalationTriggers: [],
            openingMessage: '',
        },
        systemPrompt: 'You are a marketing communications specialist. Create engaging, friendly messages for promotions, updates, and customer celebrations.',
        allowExternalUse: true,
        temperature: 0.8,
        maxTokens: 512,
    },
];

export function generateSystemPrompt(assistant: Partial<Assistant>): string {
    const { name, description, personality, behaviorRules } = assistant;

    const toneDescription = personality?.tone ? `Your tone is ${personality.tone}.` : '';
    const styleDescription = personality?.style ? `Your communication style is ${personality.style}.` : '';
    const lengthDescription = personality?.responseLength
        ? `Keep responses ${personality.responseLength === 'brief' ? 'brief (1-2 sentences)' : personality.responseLength === 'detailed' ? 'detailed (3-5 sentences)' : 'moderate (2-3 sentences)'}.`
        : '';

    const rulesSection = behaviorRules?.responseRules?.length
        ? `\n\nRULES TO FOLLOW:\n${behaviorRules.responseRules.map(r => `- ${r}`).join('\n')}`
        : '';

    const neverSection = behaviorRules?.neverSay?.length
        ? `\n\nNEVER SAY:\n${behaviorRules.neverSay.map(r => `- "${r}"`).join('\n')}`
        : '';

    const escalationSection = behaviorRules?.escalationTriggers?.length
        ? `\n\nESCALATE TO HUMAN WHEN:\n${behaviorRules.escalationTriggers.map(r => `- ${r}`).join('\n')}`
        : '';

    return `You are ${name || 'an AI assistant'}. ${description || ''}

${toneDescription} ${styleDescription} ${lengthDescription}
${rulesSection}${neverSection}${escalationSection}

Always be helpful, accurate, and respectful. Use the provided knowledge base to answer questions.`.trim();
}

export function createAssistantFromTemplate(
    template: AssistantTemplate,
    partnerId: string,
    createdBy: string
): Omit<Assistant, 'createdAt' | 'updatedAt'> {
    const systemPrompt = generateSystemPrompt({
        name: template.name,
        description: template.description,
        personality: template.personality,
        behaviorRules: template.behaviorRules as AssistantBehaviorRules,
    });

    return {
        id: `custom-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        partnerId,
        type: 'custom',
        templateId: template.id,
        name: template.name,
        description: template.description,
        avatar: template.avatar,
        color: template.color,
        personality: template.personality,
        documentConfig: {
            useAllDocuments: true,
            attachedDocumentIds: [],
            externalDocumentIds: [],
        },
        behaviorRules: {
            responseRules: template.behaviorRules.responseRules || [],
            neverSay: template.behaviorRules.neverSay || [],
            escalationTriggers: template.behaviorRules.escalationTriggers || [],
            openingMessage: template.behaviorRules.openingMessage || '',
        },
        systemPrompt,
        systemPromptAutoGenerated: true,
        allowExternalUse: true,
        isActive: true,
        temperature: 0.7,
        maxTokens: 1024,
        createdBy,
        usageCount: 0,
    };
}

export function getAssistantColorClasses(color: string): {
    gradient: string;
    bgLight: string;
    text: string;
    border: string;
    ring: string;
} {
    const colorMap: Record<string, { gradient: string; bgLight: string; text: string; border: string; ring: string }> = {
        blue: {
            gradient: 'from-blue-500 to-cyan-500',
            bgLight: 'bg-blue-50',
            text: 'text-blue-600',
            border: 'border-blue-200',
            ring: 'ring-blue-500/20',
        },
        emerald: {
            gradient: 'from-emerald-500 to-green-500',
            bgLight: 'bg-emerald-50',
            text: 'text-emerald-600',
            border: 'border-emerald-200',
            ring: 'ring-emerald-500/20',
        },
        violet: {
            gradient: 'from-violet-500 to-purple-500',
            bgLight: 'bg-violet-50',
            text: 'text-violet-600',
            border: 'border-violet-200',
            ring: 'ring-violet-500/20',
        },
        amber: {
            gradient: 'from-amber-500 to-orange-500',
            bgLight: 'bg-amber-50',
            text: 'text-amber-600',
            border: 'border-amber-200',
            ring: 'ring-amber-500/20',
        },
        rose: {
            gradient: 'from-rose-500 to-pink-500',
            bgLight: 'bg-rose-50',
            text: 'text-rose-600',
            border: 'border-rose-200',
            ring: 'ring-rose-500/20',
        },
        cyan: {
            gradient: 'from-cyan-500 to-teal-500',
            bgLight: 'bg-cyan-50',
            text: 'text-cyan-600',
            border: 'border-cyan-200',
            ring: 'ring-cyan-500/20',
        },
        orange: {
            gradient: 'from-orange-500 to-red-500',
            bgLight: 'bg-orange-50',
            text: 'text-orange-600',
            border: 'border-orange-200',
            ring: 'ring-orange-500/20',
        },
        indigo: {
            gradient: 'from-indigo-500 to-blue-500',
            bgLight: 'bg-indigo-50',
            text: 'text-indigo-600',
            border: 'border-indigo-200',
            ring: 'ring-indigo-500/20',
        },
    };

    return colorMap[color] || colorMap.blue;
}
