# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9b7ba5ff839a378d8b61c7354d96e226"
name = "PingBoxShop"
application_url = "https://pingbox.io"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locales,read_orders,read_product_listings,read_products,read_shipping"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://pingbox.io/api/auth/shopify/callback" ]

[app_preferences]
url = "https://pingbox.io/partner/apps/shopify"
