"use server";

import { db } from '@/lib/firebase-admin';
import { Timestamp } from 'firebase-admin/firestore';
import {
    Assistant,
    AssistantTemplate,
    ASSISTANT_TEMPLATES,
    ESSENTIAL_ASSISTANT_DEFAULTS,
    generateSystemPrompt,
    createAssistantFromTemplate,
} from '@/lib/types-assistant';

const serializeAssistant = (data: any, id: string): Assistant => {
    return {
        ...data,
        id,
        createdAt: data.createdAt?.toDate ? data.createdAt.toDate() : (data.createdAt instanceof Date ? data.createdAt : new Date(data.createdAt || Date.now())),
        updatedAt: data.updatedAt?.toDate ? data.updatedAt.toDate() : (data.updatedAt instanceof Date ? data.updatedAt : new Date(data.updatedAt || Date.now())),
    } as Assistant;
};

export async function getAssistantsAction(
    partnerId: string
): Promise<{ success: boolean; assistants?: Assistant[]; error?: string }> {
    try {
        if (!db) {
            return { success: false, error: 'Database unavailable' };
        }

        const snapshot = await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .orderBy('createdAt', 'desc')
            .get();

        const customAssistants: Assistant[] = snapshot.docs.map(doc =>
            serializeAssistant(doc.data(), doc.id)
        );

        const essentialIds = customAssistants
            .filter(a => a.type === 'essential')
            .map(a => a.id);

        const missingEssentials = ESSENTIAL_ASSISTANT_DEFAULTS
            .filter(e => !essentialIds.includes(e.id!))
            .map(e => ({
                ...e,
                partnerId,
                documentConfig: e.documentConfig || {
                    useAllDocuments: e.id !== 'essential-general_mode',
                    attachedDocumentIds: [],
                    externalDocumentIds: [],
                },
                systemPromptAutoGenerated: true,
                isActive: true,
                createdAt: new Date(),
                updatedAt: new Date(),
                usageCount: 0,
            })) as Assistant[];

        const allAssistants = [...missingEssentials, ...customAssistants];

        return { success: true, assistants: allAssistants };
    } catch (error: any) {
        console.error('Get assistants error:', error);
        return { success: false, error: error.message };
    }
}

export async function createAssistantAction(
    partnerId: string,
    data: Omit<Assistant, 'id' | 'partnerId' | 'createdAt' | 'updatedAt' | 'usageCount'>,
    createdBy: string
): Promise<{ success: boolean; assistantId?: string; error?: string }> {
    try {
        if (!db) {
            return { success: false, error: 'Database unavailable' };
        }

        const assistantId = `custom-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

        const assistantData: Omit<Assistant, 'id'> & { id: string } = {
            ...data,
            id: assistantId,
            partnerId,
            type: 'custom',
            createdAt: Timestamp.now(),
            updatedAt: Timestamp.now(),
            createdBy,
            usageCount: 0,
        };

        await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(assistantId)
            .set(assistantData);

        console.log(`✅ Assistant created: ${assistantId}`);

        return { success: true, assistantId };
    } catch (error: any) {
        console.error('Create assistant error:', error);
        return { success: false, error: error.message };
    }
}

export async function createAssistantFromTemplateAction(
    partnerId: string,
    templateId: string,
    createdBy: string
): Promise<{ success: boolean; assistantId?: string; assistant?: Assistant; error?: string }> {
    try {
        if (!db) {
            return { success: false, error: 'Database unavailable' };
        }

        const template = ASSISTANT_TEMPLATES.find(t => t.id === templateId);
        if (!template) {
            return { success: false, error: 'Template not found' };
        }

        const assistantData = createAssistantFromTemplate(template, partnerId, createdBy);

        const fullAssistant: Assistant = {
            ...assistantData,
            createdAt: Timestamp.now() as any,
            updatedAt: Timestamp.now() as any,
        };

        await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(assistantData.id)
            .set(fullAssistant);

        console.log(`✅ Assistant created from template: ${assistantData.id}`);

        const serializedAssistant = serializeAssistant(fullAssistant, assistantData.id);

        return { success: true, assistantId: assistantData.id, assistant: serializedAssistant };
    } catch (error: any) {
        console.error('Create assistant from template error:', error);
        return { success: false, error: error.message };
    }
}

export async function updateAssistantAction(
    partnerId: string,
    assistantId: string,
    updates: Partial<Assistant>
): Promise<{ success: boolean; error?: string }> {
    try {
        if (!db) {
            return { success: false, error: 'Database unavailable' };
        }

        const safeUpdates = { ...updates };
        delete (safeUpdates as any).id;
        delete (safeUpdates as any).partnerId;
        delete (safeUpdates as any).createdAt;
        delete (safeUpdates as any).createdBy;

        await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(assistantId)
            .update({
                ...safeUpdates,
                updatedAt: Timestamp.now(),
            });

        console.log(`✅ Assistant updated: ${assistantId}`);

        return { success: true };
    } catch (error: any) {
        console.error('Update assistant error:', error);
        return { success: false, error: error.message };
    }
}

export async function deleteAssistantAction(
    partnerId: string,
    assistantId: string
): Promise<{ success: boolean; error?: string }> {
    try {
        if (!db) {
            return { success: false, error: 'Database unavailable' };
        }

        if (assistantId.startsWith('essential-')) {
            return { success: false, error: 'Cannot delete essential assistants' };
        }

        await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(assistantId)
            .delete();

        console.log(`✅ Assistant deleted: ${assistantId}`);

        return { success: true };
    } catch (error: any) {
        console.error('Delete assistant error:', error);
        return { success: false, error: error.message };
    }
}

export async function toggleAssistantActiveAction(
    partnerId: string,
    assistantId: string,
    isActive: boolean
): Promise<{ success: boolean; error?: string }> {
    try {
        if (!db) {
            return { success: false, error: 'Database unavailable' };
        }

        await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(assistantId)
            .update({
                isActive,
                updatedAt: Timestamp.now(),
            });

        return { success: true };
    } catch (error: any) {
        console.error('Toggle assistant error:', error);
        return { success: false, error: error.message };
    }
}

export async function duplicateAssistantAction(
    partnerId: string,
    assistantId: string,
    createdBy: string
): Promise<{ success: boolean; newAssistantId?: string; error?: string }> {
    try {
        if (!db) {
            return { success: false, error: 'Database unavailable' };
        }

        const docRef = await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(assistantId)
            .get();

        if (!docRef.exists) {
            return { success: false, error: 'Assistant not found' };
        }

        const original = docRef.data() as Assistant;
        const newId = `custom-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

        const duplicate: Assistant = {
            ...original,
            id: newId,
            name: `${original.name} (Copy)`,
            type: 'custom',
            createdAt: Timestamp.now() as any,
            updatedAt: Timestamp.now() as any,
            createdBy,
            usageCount: 0,
        };

        await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(newId)
            .set(duplicate);

        return { success: true, newAssistantId: newId };
    } catch (error: any) {
        console.error('Duplicate assistant error:', error);
        return { success: false, error: error.message };
    }
}

export async function regenerateSystemPromptAction(
    partnerId: string,
    assistantId: string
): Promise<{ success: boolean; systemPrompt?: string; error?: string }> {
    try {
        if (!db) {
            return { success: false, error: 'Database unavailable' };
        }

        const docRef = await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(assistantId)
            .get();

        if (!docRef.exists) {
            return { success: false, error: 'Assistant not found' };
        }

        const assistant = docRef.data() as Assistant;
        const newPrompt = generateSystemPrompt(assistant);

        await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(assistantId)
            .update({
                systemPrompt: newPrompt,
                systemPromptAutoGenerated: true,
                systemPromptManualOverride: null,
                updatedAt: Timestamp.now(),
            });

        return { success: true, systemPrompt: newPrompt };
    } catch (error: any) {
        console.error('Regenerate system prompt error:', error);
        return { success: false, error: error.message };
    }
}

export async function getAssistantTemplatesAction(): Promise<{
    success: boolean;
    templates?: AssistantTemplate[];
}> {
    return { success: true, templates: ASSISTANT_TEMPLATES };
}

export async function incrementAssistantUsageAction(
    partnerId: string,
    assistantId: string
): Promise<{ success: boolean }> {
    try {
        if (!db || !assistantId) {
            return { success: false };
        }

        const { FieldValue } = await import('firebase-admin/firestore');

        await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(assistantId)
            .update({
                usageCount: FieldValue.increment(1),
            });

        return { success: true };
    } catch (error) {
        console.error('Increment usage error:', error);
        return { success: false };
    }
}

export async function getActiveAssistantsAction(
    partnerId: string
): Promise<{ success: boolean; assistants?: Array<{ id: string; name: string; avatar: string; color: string; type: string; description?: string }>; error?: string }> {
    try {
        if (!db) {
            return { success: false, error: 'Database unavailable' };
        }

        // Query agents that are explicitly stored in the partner's hubAgents collection and are active
        const snapshot = await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .where('isActive', '==', true)
            .get();

        const storedAssistants = snapshot.docs.map(doc => {
            const data = doc.data();
            return {
                id: doc.id,
                name: data.name || 'Unnamed',
                avatar: data.avatar || '🤖',
                color: data.color || 'blue',
                type: data.type || 'custom',
                description: data.description || '',
            };
        });

        // Get the IDs of stored assistants
        const storedIds = storedAssistants.map(a => a.id);

        // Add essential defaults that aren't already stored
        // This ensures partners always have access to essential agents in the inbox
        const missingEssentials = ESSENTIAL_ASSISTANT_DEFAULTS
            .filter(e => e.id && !storedIds.includes(e.id))
            .map(e => ({
                id: e.id!,
                name: e.name || 'Unnamed',
                avatar: e.avatar || '🤖',
                color: e.color || 'blue',
                type: e.type || 'essential',
                description: e.description || '',
            }));

        const allAssistants = [...storedAssistants, ...missingEssentials];

        return { success: true, assistants: allAssistants };
    } catch (error: any) {
        console.error('Get active assistants error:', error);
        return { success: false, error: error.message };
    }
}

export async function getAssistantByIdAction(
    partnerId: string,
    assistantId: string
): Promise<{ success: boolean; assistant?: Assistant; error?: string }> {
    try {
        if (!db) {
            return { success: false, error: 'Database unavailable' };
        }

        const docRef = await db
            .collection('partners')
            .doc(partnerId)
            .collection('hubAgents')
            .doc(assistantId)
            .get();

        if (!docRef.exists) {
            const essentialDefault = ESSENTIAL_ASSISTANT_DEFAULTS.find(e => e.id === assistantId);
            if (essentialDefault) {
                return {
                    success: true,
                    assistant: {
                        ...essentialDefault,
                        partnerId,
                        isActive: true,
                        createdAt: new Date(),
                        updatedAt: new Date(),
                        usageCount: 0,
                    } as Assistant,
                };
            }
            return { success: false, error: 'Assistant not found' };
        }

        return { success: true, assistant: serializeAssistant(docRef.data(), docRef.id) };
    } catch (error: any) {
        console.error('Get assistant by ID error:', error);
        return { success: false, error: error.message };
    }
}