// ============================================================================
// FIELD & CATEGORY DEFINITIONS
// ============================================================================

export type ModuleFieldType =
    | 'text'
    | 'number'
    | 'currency'
    | 'select'
    | 'multi_select'
    | 'toggle'
    | 'tags'
    | 'textarea'
    | 'image'
    | 'date'
    | 'time'
    | 'duration'
    | 'url'
    | 'email'
    | 'phone';

export interface ModuleFieldDefinition {
    id: string;
    name: string;
    type: ModuleFieldType;
    description?: string;
    isRequired: boolean;
    isSearchable: boolean;
    showInList: boolean;
    showInCard: boolean;
    placeholder?: string;
    options?: string[];
    defaultValue?: any;
    validation?: {
        min?: number;
        max?: number;
        minLength?: number;
        maxLength?: number;
        pattern?: string;
        patternMessage?: string;
    };
    conditionalOn?: {
        fieldId: string;
        value: any;
    };
    order: number;
}

export interface ModuleCategoryDefinition {
    id: string;
    name: string;
    icon?: string;
    description?: string;
    color?: string;
    order: number;
}

export interface ModuleSchema {
    fields: ModuleFieldDefinition[];
    categories: ModuleCategoryDefinition[];
}

// ============================================================================
// SCHEMA VERSIONING
// ============================================================================

export interface ModuleSchemaVersion {
    version: number;
    fields: ModuleFieldDefinition[];
    categories: ModuleCategoryDefinition[];
    generatedAt: string;
    generatedBy: 'ai' | 'manual';
    aiModel?: string;
    aiPromptHash?: string;
    status: 'active' | 'deprecated' | 'sunset';
    sunsetDate?: string;
    changeNotes?: string;
}

export interface ModuleFieldMapping {
    oldFieldId: string;
    newFieldId: string;
    transform?: 'direct' | 'rename' | 'convert';
    convertFn?: string;
}

export interface ModuleMigration {
    id: string;
    fromVersion: number;
    toVersion: number;
    fieldMappings: ModuleFieldMapping[];
    defaultValues: Record<string, any>;
    removedFields: string[];
    addedFields: string[];
    createdAt: string;
    createdBy: string;
    isAutoGenerated: boolean;
}

// ============================================================================
// SYSTEM MODULE (Admin-managed template)
// ============================================================================

export type ModulePriceType = 'one_time' | 'per_night' | 'per_hour' | 'per_session' | 'per_day' | 'per_week' | 'per_month' | 'per_year' | 'custom';

export interface SystemModuleSettings {
    allowCustomFields: boolean;
    allowCustomCategories: boolean;
    maxItems: number;
    maxCustomFields: number;
    maxCustomCategories: number;
    requiresPrice: boolean;
    requiresImage: boolean;
    requiresCategory: boolean;
    enableVariants: boolean;
    enableInventoryTracking: boolean;
    minSchemaVersion: number;
}

export interface SystemModule {
    id: string;
    slug: string;
    name: string;
    description: string;
    icon: string;
    color: string;

    currentVersion: number;
    schema: ModuleSchema;
    schemaHistory: Record<number, ModuleSchemaVersion>;
    migrations: Record<string, ModuleMigration>;

    itemLabel: string;
    itemLabelPlural: string;
    priceLabel: string;
    priceType: ModulePriceType;
    defaultCurrency: string;

    settings: SystemModuleSettings;

    applicableIndustries: string[];
    applicableFunctions: string[];

    agentConfig?: ModuleAgentConfig;

    status: 'draft' | 'active' | 'deprecated';

    usageCount: number;
    lastUsedAt?: string;

    createdAt: string;
    updatedAt: string;
    createdBy: string;
}

// ============================================================================
// MODULE ASSIGNMENT (Taxonomy → Module mapping)
// ============================================================================

export interface ModuleAssignmentEntry {
    moduleSlug: string;
    isRequired: boolean;
    isDefault: boolean;
    order: number;
}

export interface ModuleAssignment {
    id: string;
    industryId: string;
    functionId: string;
    industryName: string;
    functionName: string;
    modules: ModuleAssignmentEntry[];
    createdAt: string;
    updatedAt: string;
    updatedBy: string;
}

// ============================================================================
// PARTNER MODULE (Partner's enabled module instance)
// ============================================================================

export interface PartnerModule {
    id: string;
    partnerId: string;
    moduleSlug: string;
    moduleId: string;
    name: string;
    enabled: boolean;

    schemaVersion: number;
    upgradeAvailable: boolean;
    latestVersion: number;
    lastUpgradeCheck: string;

    customFields: PartnerCustomField[];
    customCategories: PartnerCustomCategory[];

    _legacyFields?: Record<string, any>;

    itemCount: number;
    activeItemCount: number;
    lastItemAddedAt?: string;
    lastItemUpdatedAt?: string;

    settings: {
        defaultCategory?: string;
        defaultCurrency: string;
        showInactiveItems: boolean;
        itemsPerPage: number;
    };

    createdAt: string;
    updatedAt: string;
}

// ============================================================================
// MODULE ITEM (Partner's actual inventory entry)
// ============================================================================

export interface ModuleItemVariant {
    id: string;
    name: string;
    sku?: string;
    price?: number;
    stock?: number;
    attributes: Record<string, any>;
}

export interface ModuleItem {
    id: string;
    moduleId: string;
    partnerId: string;

    name: string;
    description?: string;
    category: string;

    price?: number;
    compareAtPrice?: number;
    currency: string;

    images: string[];
    thumbnail?: string;

    fields: Record<string, any>;

    variants?: ModuleItemVariant[];

    stock?: number;
    trackInventory: boolean;

    isActive: boolean;
    isFeatured: boolean;
    sortOrder: number;

    _schemaVersion: number;
    _legacyFields?: Record<string, any>;
    /**
     * Marks how this item was seeded. Set by sample-data actions
     * (fixture / generator / minimal). Absent for partner-authored
     * items created via ItemEditor / Import / API. Used by the
     * "Clear sample data" flow on /partner/relay/data to delete
     * only auto-seeded items, preserving partner edits.
     */
    _seedSource?: 'fixture' | 'generator' | 'minimal';

    ragText?: string;
    ragKeywords?: string[];
    ragUpdatedAt?: string;

    seoTitle?: string;
    seoDescription?: string;

    createdAt: string;
    updatedAt: string;
    createdBy: string;
    updatedBy?: string;
}

// ============================================================================
// MODULE CATEGORY (Partner's custom category)
// ============================================================================

export interface PartnerModuleCategory {
    id: string;
    moduleId: string;
    partnerId: string;
    name: string;
    icon?: string;
    description?: string;
    color?: string;
    parentId?: string;
    order: number;
    itemCount: number;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
}

// ============================================================================
// MIGRATION TYPES
// ============================================================================

export interface MigrationPreview {
    fromVersion: number;
    toVersion: number;
    keptFields: { oldId: string; newId: string; name: string }[];
    addedFields: { id: string; name: string; defaultValue: any }[];
    removedFields: { id: string; name: string }[];
    renamedFields: { oldId: string; newId: string; oldName: string; newName: string }[];
    itemCount: number;
    estimatedTime: number;
}

export interface MigrationResult {
    success: boolean;
    fromVersion: number;
    toVersion: number;
    itemsMigrated: number;
    itemsFailed: number;
    errors: { itemId: string; itemName: string; error: string }[];
    legacyDataPreserved: number;
    startedAt: string;
    completedAt: string;
    duration: number;
}

// ============================================================================
// MODULE AGENT CONFIG (AI agent metadata per module)
// ============================================================================

export interface ModuleAgentConfig {
    /** How the Relay widget renders items: 'card', 'list', or 'carousel' */
    relayBlockType: 'card' | 'list' | 'carousel';
    /** Field IDs to show in Relay widget display */
    displayFields: string[];
    /** Field ID or template for the card title (e.g. "name" or "{name} - {location}") */
    cardTitle: string;
    /** Field ID or template for the card subtitle */
    cardSubtitle?: string;
    /** Field ID for the price display */
    cardPrice?: string;
    /** Field ID for the card image */
    cardImage?: string;
    /** Field IDs used for comparison features */
    comparisonFields: string[];
    /** Field IDs that are searchable via AI */
    searchableFields: string[];
    /** Field IDs available as broadcast template variables */
    broadcastVariables: string[];
    /** Template string describing how to summarize this module's items for inbox AI context */
    inboxContext: string;
}

// ============================================================================
// MODULE DISCOVERY (AI-discovered modules for a business function)
// ============================================================================

export interface DiscoveredModule {
    name: string;
    slug: string;
    description: string;
    icon: string;
    itemLabel: string;
    itemLabelPlural: string;
    priceType: ModulePriceType;
    priceLabel: string;
    estimatedFieldCount: number;
    agentConfig: ModuleAgentConfig;
    /** Whether this module is selected for generation */
    selected?: boolean;
}

export interface ModuleDiscoveryTemplate {
    id: string;
    industryId: string;
    functionId: string;
    industryName: string;
    functionName: string;
    modules: DiscoveredModule[];
    generatedAt: string;
    generatedBy: string;
}

// ============================================================================
// PARTNER CUSTOM FIELDS & CATEGORIES
// ============================================================================

export interface PartnerCustomField {
    id: string;
    name: string;
    type: ModuleFieldType;
    description?: string;
    isRequired: boolean;
    isSearchable: boolean;
    showInList: boolean;
    showInCard: boolean;
    placeholder?: string;
    options?: string[];
    defaultValue?: any;
    validation?: {
        min?: number;
        max?: number;
        minLength?: number;
        maxLength?: number;
        pattern?: string;
        patternMessage?: string;
    };
    order: number;
    /** When the partner added this custom field */
    addedAt: string;
    /** Who added this custom field */
    addedBy: string;
}

export interface PartnerCustomCategory {
    id: string;
    name: string;
    icon?: string;
    description?: string;
    color?: string;
    order: number;
    /** When the partner added this custom category */
    addedAt: string;
    /** Who added this custom category */
    addedBy: string;
}

// ============================================================================
// AI GENERATION TYPES
// ============================================================================

export interface ModuleGenerationRequest {
    moduleSlug?: string;
    industryId: string;
    functionId: string;
    industryName: string;
    functionName: string;
    countryCode: string;
    existingSchema?: ModuleSchema;
    enhancementPrompt?: string;
    includeIntegrations?: boolean;
    includeAITools?: boolean;
}

export interface ModuleGenerationResult {
    success: boolean;
    schema?: ModuleSchema;
    suggestedItems?: Partial<ModuleItem>[];
    integrations?: { id: string; name: string; description: string; category: string }[];
    aiTools?: { id: string; name: string; description: string; useCase: string }[];
    error?: string;
    generatedAt: string;
    model: string;
    promptTokens: number;
    completionTokens: number;
}

// ============================================================================
// API RESPONSE TYPES
// ============================================================================

export interface ModulesActionResponse<T = void> {
    success: boolean;
    data?: T;
    error?: string;
    code?: string;
}

export interface PaginatedResponse<T> {
    items: T[];
    total: number;
    page: number;
    pageSize: number;
    hasMore: boolean;
}
