// ============================================================================
// FIELD & CATEGORY DEFINITIONS
// ============================================================================

export type ModuleFieldType =
    | 'text'
    | 'number'
    | 'currency'
    | 'select'
    | 'multi_select'
    | 'toggle'
    | 'tags'
    | 'textarea'
    | 'image'
    | 'date'
    | 'time'
    | 'duration'
    | 'url'
    | 'email'
    | 'phone';

export interface ModuleFieldDefinition {
    id: string;
    name: string;
    type: ModuleFieldType;
    description?: string;
    isRequired: boolean;
    isSearchable: boolean;
    showInList: boolean;
    showInCard: boolean;
    placeholder?: string;
    options?: string[];
    defaultValue?: any;
    validation?: {
        min?: number;
        max?: number;
        minLength?: number;
        maxLength?: number;
        pattern?: string;
        patternMessage?: string;
    };
    conditionalOn?: {
        fieldId: string;
        value: any;
    };
    order: number;
}

export interface ModuleCategoryDefinition {
    id: string;
    name: string;
    icon?: string;
    description?: string;
    color?: string;
    order: number;
}

export interface ModuleSchema {
    fields: ModuleFieldDefinition[];
    categories: ModuleCategoryDefinition[];
}

// ============================================================================
// SCHEMA VERSIONING
// ============================================================================

export interface ModuleSchemaVersion {
    version: number;
    fields: ModuleFieldDefinition[];
    categories: ModuleCategoryDefinition[];
    generatedAt: string;
    generatedBy: 'ai' | 'manual';
    aiModel?: string;
    aiPromptHash?: string;
    status: 'active' | 'deprecated' | 'sunset';
    sunsetDate?: string;
    changeNotes?: string;
}

export interface ModuleFieldMapping {
    oldFieldId: string;
    newFieldId: string;
    transform?: 'direct' | 'rename' | 'convert';
    convertFn?: string;
}

export interface ModuleMigration {
    id: string;
    fromVersion: number;
    toVersion: number;
    fieldMappings: ModuleFieldMapping[];
    defaultValues: Record<string, any>;
    removedFields: string[];
    addedFields: string[];
    createdAt: string;
    createdBy: string;
    isAutoGenerated: boolean;
}

// ============================================================================
// SYSTEM MODULE (Admin-managed template)
// ============================================================================

export type ModulePriceType = 'one_time' | 'per_night' | 'per_hour' | 'per_session' | 'per_day' | 'per_week' | 'per_month' | 'per_year' | 'custom';

export interface SystemModuleSettings {
    allowCustomFields: boolean;
    allowCustomCategories: boolean;
    maxItems: number;
    maxCustomFields: number;
    maxCustomCategories: number;
    requiresPrice: boolean;
    requiresImage: boolean;
    requiresCategory: boolean;
    enableVariants: boolean;
    enableInventoryTracking: boolean;
    minSchemaVersion: number;
}

export interface SystemModule {
    id: string;
    slug: string;
    name: string;
    description: string;
    icon: string;
    color: string;

    currentVersion: number;
    schema: ModuleSchema;
    schemaHistory: Record<number, ModuleSchemaVersion>;
    migrations: Record<string, ModuleMigration>;

    itemLabel: string;
    itemLabelPlural: string;
    priceLabel: string;
    priceType: ModulePriceType;
    defaultCurrency: string;

    settings: SystemModuleSettings;

    applicableIndustries: string[];
    applicableFunctions: string[];

    status: 'draft' | 'active' | 'deprecated';

    usageCount: number;
    lastUsedAt?: string;

    createdAt: string;
    updatedAt: string;
    createdBy: string;
}

// ============================================================================
// MODULE ASSIGNMENT (Taxonomy → Module mapping)
// ============================================================================

export interface ModuleAssignmentEntry {
    moduleSlug: string;
    isRequired: boolean;
    isDefault: boolean;
    order: number;
}

export interface ModuleAssignment {
    id: string;
    industryId: string;
    functionId: string;
    industryName: string;
    functionName: string;
    modules: ModuleAssignmentEntry[];
    createdAt: string;
    updatedAt: string;
    updatedBy: string;
}

// ============================================================================
// PARTNER MODULE (Partner's enabled module instance)
// ============================================================================

export interface PartnerModule {
    id: string;
    partnerId: string;
    moduleSlug: string;
    moduleId: string;
    name: string;
    enabled: boolean;

    schemaVersion: number;
    upgradeAvailable: boolean;
    latestVersion: number;
    lastUpgradeCheck: string;

    customFields: ModuleFieldDefinition[];
    customCategories: ModuleCategoryDefinition[];

    _legacyFields?: Record<string, any>;

    itemCount: number;
    activeItemCount: number;
    lastItemAddedAt?: string;
    lastItemUpdatedAt?: string;

    settings: {
        defaultCategory?: string;
        defaultCurrency: string;
        showInactiveItems: boolean;
        itemsPerPage: number;
    };

    createdAt: string;
    updatedAt: string;
}

// ============================================================================
// MODULE ITEM (Partner's actual inventory entry)
// ============================================================================

export interface ModuleItemVariant {
    id: string;
    name: string;
    sku?: string;
    price?: number;
    stock?: number;
    attributes: Record<string, any>;
}

export interface ModuleItem {
    id: string;
    moduleId: string;
    partnerId: string;

    name: string;
    description?: string;
    category: string;

    price?: number;
    compareAtPrice?: number;
    currency: string;

    images: string[];
    thumbnail?: string;

    fields: Record<string, any>;

    variants?: ModuleItemVariant[];

    stock?: number;
    trackInventory: boolean;

    isActive: boolean;
    isFeatured: boolean;
    sortOrder: number;

    _schemaVersion: number;
    _legacyFields?: Record<string, any>;

    ragText?: string;
    ragKeywords?: string[];
    ragUpdatedAt?: string;

    seoTitle?: string;
    seoDescription?: string;

    createdAt: string;
    updatedAt: string;
    createdBy: string;
    updatedBy?: string;
}

// ============================================================================
// MODULE CATEGORY (Partner's custom category)
// ============================================================================

export interface PartnerModuleCategory {
    id: string;
    moduleId: string;
    partnerId: string;
    name: string;
    icon?: string;
    description?: string;
    color?: string;
    parentId?: string;
    order: number;
    itemCount: number;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
}

// ============================================================================
// MIGRATION TYPES
// ============================================================================

export interface MigrationPreview {
    fromVersion: number;
    toVersion: number;
    keptFields: { oldId: string; newId: string; name: string }[];
    addedFields: { id: string; name: string; defaultValue: any }[];
    removedFields: { id: string; name: string }[];
    renamedFields: { oldId: string; newId: string; oldName: string; newName: string }[];
    itemCount: number;
    estimatedTime: number;
}

export interface MigrationResult {
    success: boolean;
    fromVersion: number;
    toVersion: number;
    itemsMigrated: number;
    itemsFailed: number;
    errors: { itemId: string; itemName: string; error: string }[];
    legacyDataPreserved: number;
    startedAt: string;
    completedAt: string;
    duration: number;
}

// ============================================================================
// AI GENERATION TYPES
// ============================================================================

export interface ModuleGenerationRequest {
    moduleSlug?: string;
    industryId: string;
    functionId: string;
    industryName: string;
    functionName: string;
    countryCode: string;
    existingSchema?: ModuleSchema;
    enhancementPrompt?: string;
    includeIntegrations?: boolean;
    includeAITools?: boolean;
}

export interface ModuleGenerationResult {
    success: boolean;
    schema?: ModuleSchema;
    suggestedItems?: Partial<ModuleItem>[];
    integrations?: { id: string; name: string; description: string; category: string }[];
    aiTools?: { id: string; name: string; description: string; useCase: string }[];
    error?: string;
    generatedAt: string;
    model: string;
    promptTokens: number;
    completionTokens: number;
}

// ============================================================================
// API RESPONSE TYPES
// ============================================================================

export interface ModulesActionResponse<T = void> {
    success: boolean;
    data?: T;
    error?: string;
    code?: string;
}

export interface PaginatedResponse<T> {
    items: T[];
    total: number;
    page: number;
    pageSize: number;
    hasMore: boolean;
}
