import { customAlphabet } from 'nanoid';
import type { ModuleFieldDefinition, ModuleSchema, ModuleMigration, ModuleItem } from './types';

const nanoid = customAlphabet('0123456789abcdefghijklmnopqrstuvwxyz', 12);

export function generateModuleId(): string {
    return `mod_${nanoid()}`;
}

export function generateItemId(): string {
    return `item_${nanoid()}`;
}

export function generateCategoryId(): string {
    return `cat_${nanoid()}`;
}

export function generateFieldId(): string {
    return `fld_${nanoid()}`;
}

export function slugify(text: string): string {
    return text
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '')
        .substring(0, 50);
}

export function getFieldDefaultValue(type: ModuleFieldDefinition['type']): any {
    switch (type) {
        case 'text':
        case 'textarea':
        case 'url':
        case 'email':
        case 'phone':
            return '';
        case 'number':
        case 'currency':
        case 'duration':
            return 0;
        case 'toggle':
            return false;
        case 'tags':
        case 'multi_select':
            return [];
        case 'select':
        case 'date':
        case 'time':
        case 'image':
            return null;
        default:
            return null;
    }
}

export function stringSimilarity(a: string, b: string): number {
    const aLower = a.toLowerCase().replace(/[^a-z0-9]/g, '');
    const bLower = b.toLowerCase().replace(/[^a-z0-9]/g, '');

    if (aLower === bLower) return 1;
    if (aLower.includes(bLower) || bLower.includes(aLower)) return 0.8;

    const aSet = new Set(aLower.split(''));
    const bSet = new Set(bLower.split(''));
    const intersection = new Set([...aSet].filter(x => bSet.has(x)));
    const union = new Set([...aSet, ...bSet]);

    return intersection.size / union.size;
}

export function createAutoMigration(
    fromVersion: number,
    toVersion: number,
    oldSchema: ModuleSchema,
    newSchema: ModuleSchema,
    createdBy: string
): ModuleMigration {
    const oldFieldMap = new Map(oldSchema.fields.map(f => [f.id, f]));
    const newFieldMap = new Map(newSchema.fields.map(f => [f.id, f]));

    const fieldMappings: ModuleMigration['fieldMappings'] = [];
    const removedFields: string[] = [];
    const addedFields: string[] = [];
    const defaultValues: Record<string, any> = {};

    for (const oldField of oldSchema.fields) {
        if (newFieldMap.has(oldField.id)) {
            fieldMappings.push({
                oldFieldId: oldField.id,
                newFieldId: oldField.id,
                transform: 'direct'
            });
        } else {
            const similarField = newSchema.fields.find(nf =>
                !oldFieldMap.has(nf.id) &&
                (stringSimilarity(nf.name, oldField.name) > 0.7 ||
                    stringSimilarity(nf.id, oldField.id) > 0.7)
            );

            if (similarField) {
                fieldMappings.push({
                    oldFieldId: oldField.id,
                    newFieldId: similarField.id,
                    transform: 'rename'
                });
            } else {
                removedFields.push(oldField.id);
            }
        }
    }

    const mappedNewIds = new Set(fieldMappings.map(m => m.newFieldId));

    for (const newField of newSchema.fields) {
        if (!mappedNewIds.has(newField.id)) {
            addedFields.push(newField.id);
            if (newField.isRequired) {
                defaultValues[newField.id] = newField.defaultValue ?? getFieldDefaultValue(newField.type);
            }
        }
    }

    return {
        id: `${fromVersion}_to_${toVersion}`,
        fromVersion,
        toVersion,
        fieldMappings,
        defaultValues,
        removedFields,
        addedFields,
        createdAt: new Date().toISOString(),
        createdBy,
        isAutoGenerated: true
    };
}

export function applyMigrationToItem(
    item: ModuleItem,
    migrations: ModuleMigration[]
): { fields: Record<string, any>; legacyFields: Record<string, any> } {
    let currentFields = { ...item.fields };
    const legacyFields: Record<string, any> = { ...item._legacyFields };

    for (const migration of migrations) {
        const newFields: Record<string, any> = {};

        for (const mapping of migration.fieldMappings) {
            if (currentFields[mapping.oldFieldId] !== undefined) {
                newFields[mapping.newFieldId] = currentFields[mapping.oldFieldId];
            }
        }

        for (const [key, value] of Object.entries(migration.defaultValues)) {
            if (newFields[key] === undefined) {
                newFields[key] = value;
            }
        }

        for (const removedField of migration.removedFields) {
            if (currentFields[removedField] !== undefined) {
                legacyFields[`v${migration.fromVersion}_${removedField}`] = currentFields[removedField];
            }
        }

        currentFields = newFields;
    }

    return { fields: currentFields, legacyFields };
}

export function generateRAGText(item: ModuleItem, schema: ModuleSchema): string {
    const parts: string[] = [item.name];

    if (item.description) {
        parts.push(item.description);
    }

    parts.push(`Category: ${item.category}`);

    if (item.price) {
        parts.push(`Price: ${item.currency} ${item.price}`);
    }

    for (const field of schema.fields) {
        if (field.isSearchable && item.fields[field.id] !== undefined) {
            const value = item.fields[field.id];
            if (Array.isArray(value)) {
                parts.push(`${field.name}: ${value.join(', ')}`);
            } else if (typeof value === 'boolean') {
                if (value) parts.push(field.name);
            } else if (value) {
                parts.push(`${field.name}: ${value}`);
            }
        }
    }

    return parts.join('. ');
}

export function formatCurrency(amount: number, currency: string = 'INR'): string {
    return new Intl.NumberFormat('en-IN', {
        style: 'currency',
        currency,
        minimumFractionDigits: 0,
        maximumFractionDigits: 2,

    }).format(amount);
}

export function cleanAndParseJSON(text: string): any {
    // 1. Try direct parse first
    try {
        return JSON.parse(text);
    } catch {
        // Continue to cleanup
    }

    // 2. Remove markdown code blocks
    let cleaned = text
        .replace(/```json\s*/gi, '')
        .replace(/```\s*/g, '')
        .trim();

    // 3. Try to extract JSON object or array
    const jsonMatch = cleaned.match(/(\{[\s\S]*\}|\[[\s\S]*\])/);
    if (jsonMatch) {
        cleaned = jsonMatch[1];
    }

    // 4. Common LLM JSON fix: Bad escaped characters
    // Replace backslashes that are NOT followed by specific JSON escape chars
    cleaned = cleaned.replace(/\\(?!["\\/bfnrtu])/g, "\\\\");

    // 5. Try parsing cleaned text
    try {
        return JSON.parse(cleaned);
    } catch (e) {
        console.error('JSON parse error. Cleaned text:', cleaned.substring(0, 500));
        // Last resort: Try to remove control characters that might be invalid
        cleaned = cleaned.replace(/[\x00-\x1F\x7F-\x9F]/g, "");
        try {
            return JSON.parse(cleaned);
        } catch (e2) {
            throw new Error(`Failed to parse JSON: ${e instanceof Error ? e.message : 'Unknown error'}`);
        }
    }
}
