import type { VerticalFamilyDef } from './_types';

export interface PlannedBlock {
  id: string;
  family: string;
  label: string;
  stage: string;
  desc: string;
  intents: string[];
  module: string | null;
  visualStyle: string;
}

export interface PlannedVertical {
  id: string;
  industryId: string;
  name: string;
  iconEmoji: string;
  accentColor: string;
  status: 'done' | 'in_progress' | 'planned';
  blockCount: number;
  subVerticalCount: number;
  uniquePatterns: string[];
  families: Record<string, VerticalFamilyDef>;
  blocks: PlannedBlock[];
  subVerticals: Array<{ id: string; name: string; blocks: string[] }>;
}

export const VERTICAL_MANIFEST: PlannedVertical[] = [
  {
    id: 'ecommerce',
    industryId: 'retail_commerce',
    name: 'Retail & E-commerce',
    iconEmoji: '🛒',
    accentColor: '#2d4a3e',
    status: 'done',
    blockCount: 10,
    subVerticalCount: 13,
    uniquePatterns: ['product cards with variant swatches', 'comparison tables', 'subscription frequency picker', 'loyalty tier progress'],
    families: {},
    blocks: [],
    subVerticals: [],
  },
  {
    id: 'hospitality',
    industryId: 'hospitality',
    name: 'Hospitality & Accommodation',
    iconEmoji: '🏨',
    accentColor: '#1e3a5f',
    status: 'in_progress',
    blockCount: 14,
    subVerticalCount: 10,
    uniquePatterns: ['room cards with bed config + amenity icons', 'availability calendar with dynamic pricing per night', 'meal plan radio selector (RO/BB/HB/AI)', 'digital check-in with upsell add-ons', 'concierge service grid'],
    families: {
      rooms: { label: 'Rooms & Units', color: '#1e3a5f' },
      booking: { label: 'Booking & Rates', color: '#b8860b' },
      property: { label: 'Property Info', color: '#0f766e' },
      dining: { label: 'Dining & Meals', color: '#b45309' },
      social_proof: { label: 'Social Proof', color: '#be185d' },
      operations: { label: 'Guest Operations', color: '#1d4ed8' },
      concierge: { label: 'Concierge Services', color: '#b8860b' },
      events: { label: 'Events & Venues', color: '#1e3a5f' },
      transport: { label: 'Transport & Logistics', color: '#7a7a70' },
    },
    blocks: [
      { id: 'room_card', family: 'rooms', label: 'Room / Unit Card', stage: 'discovery', desc: 'Browsable room card with bed config, rate breakdown, occupancy limits, and amenity icons', intents: ['rooms', 'browse', 'availability', 'stay'], module: 'items', visualStyle: 'horizontal card with gradient image, amenity icon row, per-night pricing' },
      { id: 'room_detail', family: 'rooms', label: 'Room Detail', stage: 'showcase', desc: 'Full room view — gallery strip, amenity grid, rate with savings, cancellation policy', intents: ['details', 'tell me more', 'room info'], module: 'items', visualStyle: 'hero image with thumbnail strip, 3-tier amenity chips, pricing with strikethrough' },
      { id: 'availability', family: 'booking', label: 'Availability Calendar', stage: 'showcase', desc: 'Date grid with per-night dynamic pricing, peak/standard/booked indicators', intents: ['dates', 'available', 'when', 'calendar'], module: null, visualStyle: 'month grid with color-coded prices per cell, selection range highlight, stay total' },
      { id: 'amenities', family: 'property', label: 'Amenities Grid', stage: 'discovery', desc: 'Three-tier amenity display — room, property, services', intents: ['amenities', 'facilities', 'pool', 'gym', 'spa'], module: 'items', visualStyle: 'grouped icon chips, category-colored sections' },
      { id: 'meal_plan', family: 'dining', label: 'Meal Plan Selector', stage: 'showcase', desc: 'Radio selector for RO/BB/HB/AI with per-person add-on pricing', intents: ['meals', 'breakfast', 'dinner', 'all inclusive'], module: null, visualStyle: 'radio list with monospace plan codes, description, add-on price' },
      { id: 'guest_review', family: 'social_proof', label: 'Guest Reviews', stage: 'social_proof', desc: 'Aggregate score with 5-category breakdown bars, individual reviews', intents: ['reviews', 'rating', 'feedback'], module: null, visualStyle: 'large score badge, horizontal bar chart, review cards with avatar + origin' },
      { id: 'check_in', family: 'operations', label: 'Digital Check-in', stage: 'conversion', desc: 'Pre-arrival form with guest ID, add-on upsells', intents: ['check in', 'arrive', 'pre-check'], module: null, visualStyle: 'form with booking summary header, add-on toggle chips, prominent CTA' },
      { id: 'property_gallery', family: 'property', label: 'Property Gallery', stage: 'discovery', desc: 'Asymmetric photo grid with labeled areas', intents: ['photos', 'pictures', 'gallery'], module: null, visualStyle: 'masonry grid with hero span, area labels on gradient overlays' },
      { id: 'local_experiences', family: 'concierge', label: 'Local Experiences', stage: 'discovery', desc: 'Curated tours and activities with duration and pricing', intents: ['things to do', 'activities', 'tours'], module: 'items', visualStyle: 'list items with category-colored icon circles, per-person pricing' },
      { id: 'venue_space', family: 'events', label: 'Venue / Event Space', stage: 'showcase', desc: 'Event venue with capacity, layouts, AV equipment', intents: ['event', 'wedding', 'conference'], module: 'items', visualStyle: 'hero gradient header, 3-stat grid, layout tag pills, equipment chips' },
      { id: 'camping_unit', family: 'rooms', label: 'Camping / Glamping Unit', stage: 'discovery', desc: 'Outdoor accommodation card with nature amenities', intents: ['tent', 'cabin', 'glamping'], module: 'items', visualStyle: 'green nature gradient, eco-themed amenity chips' },
      { id: 'house_rules', family: 'property', label: 'House Rules & Policies', stage: 'objection', desc: 'Structured policy table with status icons', intents: ['rules', 'policy', 'check-in time', 'cancellation'], module: null, visualStyle: 'alternating row table with status-colored icons' },
      { id: 'concierge', family: 'concierge', label: 'Concierge Request', stage: 'conversion', desc: 'In-stay service grid with special request field', intents: ['room service', 'concierge', 'request'], module: null, visualStyle: '6-cell icon grid with gold accent, textarea, send CTA' },
      { id: 'transfer', family: 'transport', label: 'Airport Transfer', stage: 'conversion', desc: 'Vehicle tier selector with capacity and pricing', intents: ['transfer', 'airport', 'pickup'], module: null, visualStyle: 'radio list with vehicle type, pax/bags icons, per-trip price' },
    ],
    subVerticals: [
      { id: 'hotels_resorts', name: 'Hotels & Resorts', blocks: ['room_card', 'room_detail', 'availability', 'amenities', 'meal_plan', 'guest_review', 'check_in', 'property_gallery', 'local_experiences', 'venue_space', 'concierge', 'transfer', 'house_rules'] },
      { id: 'budget_accommodation', name: 'Budget Accommodation', blocks: ['room_card', 'availability', 'amenities', 'guest_review', 'house_rules', 'check_in', 'transfer'] },
      { id: 'boutique_bnb', name: 'Boutique Hotels & B&Bs', blocks: ['room_card', 'room_detail', 'availability', 'amenities', 'meal_plan', 'guest_review', 'property_gallery', 'local_experiences', 'house_rules', 'concierge'] },
      { id: 'serviced_apartments', name: 'Serviced Apartments', blocks: ['room_card', 'room_detail', 'availability', 'amenities', 'house_rules', 'check_in', 'guest_review', 'local_experiences'] },
      { id: 'shared_accommodation', name: 'Shared & Hostels', blocks: ['room_card', 'availability', 'amenities', 'guest_review', 'local_experiences', 'house_rules'] },
      { id: 'vacation_rentals', name: 'Vacation Rentals & Villas', blocks: ['room_card', 'room_detail', 'availability', 'amenities', 'property_gallery', 'house_rules', 'guest_review', 'local_experiences', 'check_in'] },
      { id: 'guest_houses', name: 'Guest Houses', blocks: ['room_card', 'availability', 'amenities', 'meal_plan', 'guest_review', 'house_rules', 'local_experiences'] },
      { id: 'camping_glamping', name: 'Camping & Glamping', blocks: ['camping_unit', 'availability', 'amenities', 'property_gallery', 'local_experiences', 'house_rules', 'guest_review'] },
      { id: 'corporate_housing', name: 'Corporate Housing', blocks: ['room_card', 'room_detail', 'availability', 'amenities', 'check_in', 'transfer', 'house_rules'] },
      { id: 'event_venues', name: 'Event & Wedding Venues', blocks: ['venue_space', 'property_gallery', 'amenities', 'guest_review', 'meal_plan', 'concierge', 'house_rules'] },
    ],
  },
  {
    id: 'education',
    industryId: 'education_learning',
    name: 'Education & Learning',
    iconEmoji: '🎓',
    accentColor: '#4338ca',
    status: 'in_progress',
    blockCount: 14,
    subVerticalCount: 10,
    uniquePatterns: ['course cards with level badges + instructor avatar', 'weekly timetable grid', 'circular progress dashboard', 'assessment score with section breakdown', 'batch/cohort selector with seat fill bars', 'formal certificate display'],
    families: {
      catalog: { label: 'Course Catalog', color: '#4338ca' },
      timetable: { label: 'Scheduling', color: '#b45309' },
      people: { label: 'Instructors', color: '#be185d' },
      content: { label: 'Content & Curriculum', color: '#0f766e' },
      conversion: { label: 'Enrollment', color: '#2d6a4f' },
      tracking: { label: 'Progress & Assessment', color: '#1d4ed8' },
      pricing: { label: 'Fees & Pricing', color: '#0f766e' },
      scheduling: { label: 'Batch Management', color: '#b45309' },
      credentials: { label: 'Credentials', color: '#0f766e' },
      info: { label: 'Campus Info', color: '#7a7a70' },
    },
    blocks: [
      { id: 'course_card', family: 'catalog', label: 'Course Card', stage: 'discovery', desc: 'Browsable course with instructor, level badge, duration, student count, rating, price', intents: ['courses', 'browse', 'programs', 'classes'], module: 'items', visualStyle: 'card with gradient icon area, instructor avatar, level badge, star rating' },
      { id: 'course_detail', family: 'catalog', label: 'Course Detail', stage: 'showcase', desc: 'Full course view with instructor bio, stats, learning outcomes, pricing', intents: ['details', 'tell me more', 'syllabus'], module: 'items', visualStyle: 'hero gradient, 4-stat grid, checklist outcomes, savings badge' },
      { id: 'schedule', family: 'timetable', label: 'Schedule / Timetable', stage: 'showcase', desc: 'Weekly class grid with day columns, color-coded subject slots', intents: ['schedule', 'timetable', 'when', 'class times'], module: null, visualStyle: '5-column day grid, left-bordered color blocks, type legend' },
      { id: 'instructor', family: 'people', label: 'Instructor Profile', stage: 'discovery', desc: 'Teacher card with credentials, subject tags, rating, student count', intents: ['instructor', 'teacher', 'professor'], module: 'items', visualStyle: 'circular avatar, credential badges, subject tag pills' },
      { id: 'curriculum', family: 'content', label: 'Curriculum Outline', stage: 'showcase', desc: 'Module breakdown with numbered steps, completion status', intents: ['curriculum', 'modules', 'topics', 'syllabus'], module: null, visualStyle: 'numbered step list with completion circles, done/current badges' },
      { id: 'enrollment', family: 'conversion', label: 'Enrollment Form', stage: 'conversion', desc: 'Registration flow with course summary, payment plan selector', intents: ['enroll', 'register', 'sign up', 'apply'], module: null, visualStyle: 'summary header, input fields, radio payment plans, CTA' },
      { id: 'progress', family: 'tracking', label: 'Progress Dashboard', stage: 'social_proof', desc: 'Circular completion chart, module progress bars, next deadline', intents: ['progress', 'how am I doing', 'grades'], module: null, visualStyle: 'SVG donut chart, horizontal module bars, deadline callout' },
      { id: 'assessment', family: 'tracking', label: 'Assessment Result', stage: 'social_proof', desc: 'Test/quiz score with section breakdown, percentile ranking', intents: ['results', 'score', 'quiz', 'test'], module: null, visualStyle: 'large centered score, section bar charts, percentile badge' },
      { id: 'fee_structure', family: 'pricing', label: 'Fee Structure', stage: 'showcase', desc: 'Itemized fee table with total, scholarship indicator', intents: ['fees', 'cost', 'pricing', 'tuition'], module: null, visualStyle: 'line-item table, bold total row, green scholarship callout' },
      { id: 'student_review', family: 'social_proof', label: 'Student Reviews', stage: 'social_proof', desc: 'Aggregate score with criteria bars, individual reviews', intents: ['reviews', 'ratings', 'what do students say'], module: null, visualStyle: 'score badge, 5-criteria bars, review cards with background tags' },
      { id: 'batch_selector', family: 'scheduling', label: 'Batch / Cohort Selector', stage: 'conversion', desc: 'Batch picker with dates, times, mode, seat availability', intents: ['batch', 'start date', 'cohort', 'next batch'], module: null, visualStyle: 'radio list with mode tags, seat fill progress bars' },
      { id: 'certificate', family: 'credentials', label: 'Certificate / Credential', stage: 'social_proof', desc: 'Formal completion certificate with verification ID', intents: ['certificate', 'credential', 'diploma'], module: null, visualStyle: 'formal centered layout, gold accent, verification badge, PDF/share CTAs' },
      { id: 'resources', family: 'content', label: 'Learning Resources', stage: 'discovery', desc: 'Material library with type-coded icons', intents: ['resources', 'materials', 'downloads', 'videos'], module: null, visualStyle: 'list with type-colored icon squares, duration, open button' },
      { id: 'facility', family: 'info', label: 'Campus / Facility', stage: 'discovery', desc: 'Campus photo grid, facility list, virtual tour link', intents: ['campus', 'facility', 'location', 'labs'], module: null, visualStyle: '2-column photo grid, icon feature list, tour CTA' },
    ],
    subVerticals: [
      { id: 'early_childhood', name: 'Early Childhood Education', blocks: ['course_card', 'schedule', 'enrollment', 'fee_structure', 'facility', 'student_review'] },
      { id: 'k12_education', name: 'K–12 Education', blocks: ['course_card', 'schedule', 'curriculum', 'instructor', 'progress', 'assessment', 'fee_structure', 'student_review', 'facility'] },
      { id: 'higher_education', name: 'Higher Education', blocks: ['course_card', 'course_detail', 'curriculum', 'instructor', 'enrollment', 'fee_structure', 'batch_selector', 'certificate', 'student_review', 'facility'] },
      { id: 'test_preparation', name: 'Test Preparation', blocks: ['course_card', 'schedule', 'instructor', 'progress', 'assessment', 'fee_structure', 'batch_selector', 'student_review'] },
      { id: 'language_learning', name: 'Language Learning', blocks: ['course_card', 'schedule', 'instructor', 'progress', 'assessment', 'batch_selector', 'student_review', 'resources'] },
      { id: 'skill_vocational', name: 'Skill Development & Vocational', blocks: ['course_card', 'course_detail', 'curriculum', 'instructor', 'enrollment', 'fee_structure', 'certificate', 'student_review', 'batch_selector'] },
      { id: 'corporate_training', name: 'Corporate Training', blocks: ['course_card', 'curriculum', 'instructor', 'progress', 'certificate', 'batch_selector', 'student_review'] },
      { id: 'online_learning', name: 'Online Learning Platform', blocks: ['course_card', 'course_detail', 'curriculum', 'instructor', 'progress', 'assessment', 'resources', 'certificate', 'student_review'] },
      { id: 'academic_consulting', name: 'Academic Consulting', blocks: ['instructor', 'schedule', 'enrollment', 'fee_structure', 'student_review'] },
      { id: 'creative_arts', name: 'Creative Arts Education', blocks: ['course_card', 'schedule', 'instructor', 'enrollment', 'fee_structure', 'student_review', 'facility'] },
    ],
  },
  {
    id: 'healthcare',
    industryId: 'healthcare_medical',
    name: 'Healthcare & Medical',
    iconEmoji: '🏥',
    accentColor: '#0e7490',
    status: 'planned',
    blockCount: 14,
    subVerticalCount: 10,
    uniquePatterns: ['doctor card with specialization + availability indicator', 'symptom checker multi-step', 'appointment slot grid with doctor filter', 'insurance/payment plan card', 'prescription/treatment summary', 'patient testimonial with condition tag'],
    families: {
      practitioners: { label: 'Doctors & Staff', color: '#0e7490' },
      services: { label: 'Services & Treatments', color: '#0f766e' },
      booking: { label: 'Appointments', color: '#2d6a4f' },
      clinical: { label: 'Clinical Info', color: '#dc2626' },
      insurance: { label: 'Insurance & Billing', color: '#b45309' },
      social_proof: { label: 'Patient Reviews', color: '#be185d' },
      info: { label: 'Facility Info', color: '#7a7a70' },
    },
    blocks: [
      { id: 'doctor_card', family: 'practitioners', label: 'Doctor / Practitioner Card', stage: 'discovery', desc: 'Doctor profile with specialization, qualification badges, availability status, consultation fee', intents: ['doctor', 'specialist', 'who treats', 'available doctors'], module: 'items', visualStyle: 'avatar with green/red availability dot, qualification chips, next-available time' },
      { id: 'doctor_detail', family: 'practitioners', label: 'Doctor Detail', stage: 'showcase', desc: 'Full doctor profile — education, experience timeline, languages, procedures performed', intents: ['details', 'tell me more', 'qualifications', 'experience'], module: 'items', visualStyle: 'large avatar, education timeline, procedure count stats, language flags' },
      { id: 'treatment_card', family: 'services', label: 'Treatment / Service Card', stage: 'discovery', desc: 'Medical service with duration, prep requirements, price range, age appropriateness', intents: ['treatments', 'services', 'procedures', 'what do you offer'], module: 'items', visualStyle: 'icon circle with cross accent, duration badge, prep-required indicator, price range' },
      { id: 'symptom_checker', family: 'services', label: 'Symptom Checker', stage: 'discovery', desc: 'Multi-step guided assessment — body area, symptoms, severity, recommendation', intents: ['symptoms', 'feeling sick', 'what\'s wrong', 'diagnosis', 'check'], module: null, visualStyle: 'step progress bar, body area selector, severity scale, recommendation card' },
      { id: 'appointment_slots', family: 'booking', label: 'Appointment Slots', stage: 'conversion', desc: 'Time slot grid filtered by doctor, date, and service type', intents: ['appointment', 'book', 'schedule', 'available slots', 'when can I come'], module: null, visualStyle: 'date scroll strip, doctor filter, time slot grid with morning/afternoon sections' },
      { id: 'insurance_card', family: 'insurance', label: 'Insurance & Payment', stage: 'showcase', desc: 'Accepted insurance plans, self-pay options, EMI plans, cashless indicators', intents: ['insurance', 'payment', 'cashless', 'EMI', 'cost', 'do you accept'], module: null, visualStyle: 'insurance logo grid, cashless badge, EMI calculator, self-pay comparison' },
      { id: 'prescription', family: 'clinical', label: 'Prescription / Treatment Plan', stage: 'followup', desc: 'Post-visit treatment summary with medications, dosage, follow-up schedule', intents: ['prescription', 'medicine', 'treatment plan', 'follow up'], module: null, visualStyle: 'medication list with dosage/frequency table, follow-up date callout, pharmacy CTA' },
      { id: 'health_package', family: 'services', label: 'Health Package', stage: 'showcase', desc: 'Bundled health check-up package with tests included, price, duration', intents: ['health check', 'package', 'full body', 'tests included'], module: 'items', visualStyle: 'package card with test checklist, compare column, book CTA, fasting note' },
      { id: 'patient_review', family: 'social_proof', label: 'Patient Reviews', stage: 'social_proof', desc: 'Patient testimonials with condition-type tags, verified badge, doctor attribution', intents: ['reviews', 'patient experience', 'testimonials'], module: null, visualStyle: 'verified badge, condition tag, doctor link, privacy-first (initials only)' },
      { id: 'lab_result', family: 'clinical', label: 'Lab Results Summary', stage: 'followup', desc: 'Test results overview with normal/abnormal indicators, trend arrows', intents: ['results', 'lab report', 'test results', 'blood work'], module: null, visualStyle: 'parameter rows with normal range bars, green/red/amber indicators, trend arrows' },
      { id: 'emergency_info', family: 'info', label: 'Emergency Contact', stage: 'handoff', desc: 'Emergency numbers, ambulance, nearest ER, operating hours', intents: ['emergency', 'urgent', 'ambulance', '24 hours'], module: null, visualStyle: 'red accent header, large phone number, one-tap call buttons, map link' },
      { id: 'clinic_tour', family: 'info', label: 'Clinic / Facility Tour', stage: 'discovery', desc: 'Virtual tour with equipment highlights, certifications, accreditations', intents: ['facility', 'tour', 'equipment', 'certifications'], module: null, visualStyle: 'photo grid, certification badges (NABH, JCI), equipment highlight cards' },
      { id: 'wait_time', family: 'booking', label: 'Live Wait Time', stage: 'discovery', desc: 'Real-time queue status with estimated wait, current position, join option', intents: ['wait time', 'queue', 'how long', 'busy'], module: null, visualStyle: 'large wait time number, queue position, join queue CTA, peak indicator' },
      { id: 'medication_reminder', family: 'clinical', label: 'Medication Reminder', stage: 'followup', desc: 'Upcoming medication schedule with dosage, timing, completion tracking', intents: ['medication', 'reminder', 'pills', 'dosage', 'when to take'], module: null, visualStyle: 'timeline with pill icons, morning/noon/night sections, checkbox tracking' },
    ],
    subVerticals: [
      { id: 'general_practice', name: 'General Practice / Clinic', blocks: ['doctor_card', 'treatment_card', 'appointment_slots', 'patient_review', 'clinic_tour', 'wait_time', 'prescription', 'insurance_card'] },
      { id: 'dental_care', name: 'Dental Care', blocks: ['doctor_card', 'treatment_card', 'appointment_slots', 'patient_review', 'insurance_card', 'clinic_tour', 'health_package'] },
      { id: 'specialist_clinic', name: 'Specialist Clinic', blocks: ['doctor_card', 'doctor_detail', 'treatment_card', 'appointment_slots', 'patient_review', 'insurance_card', 'health_package', 'lab_result'] },
      { id: 'diagnostic_lab', name: 'Diagnostic & Lab Services', blocks: ['health_package', 'appointment_slots', 'lab_result', 'patient_review', 'clinic_tour'] },
      { id: 'pharmacy', name: 'Pharmacy / Medical Store', blocks: ['treatment_card', 'prescription', 'medication_reminder', 'patient_review'] },
      { id: 'physiotherapy', name: 'Physiotherapy & Rehab', blocks: ['doctor_card', 'treatment_card', 'appointment_slots', 'patient_review', 'clinic_tour', 'insurance_card'] },
      { id: 'alternative_medicine', name: 'Alternative & Traditional', blocks: ['doctor_card', 'treatment_card', 'appointment_slots', 'patient_review', 'health_package'] },
      { id: 'home_healthcare', name: 'Home Healthcare', blocks: ['doctor_card', 'treatment_card', 'appointment_slots', 'patient_review', 'prescription', 'medication_reminder'] },
      { id: 'veterinary', name: 'Veterinary Services', blocks: ['doctor_card', 'treatment_card', 'appointment_slots', 'patient_review', 'health_package', 'prescription'] },
      { id: 'mental_health', name: 'Mental Health & Therapy', blocks: ['doctor_card', 'doctor_detail', 'appointment_slots', 'patient_review', 'insurance_card'] },
    ],
  },
  {
    id: 'food_beverage',
    industryId: 'food_beverage',
    name: 'Food & Beverage',
    iconEmoji: '🍽️',
    accentColor: '#b45309',
    status: 'planned',
    blockCount: 12,
    subVerticalCount: 9,
    uniquePatterns: ['menu card with dietary icons (veg/non-veg/vegan)', 'customization builder (toppings, sides)', 'table reservation with party size', 'live order status with kitchen stages', 'chef profile with signature dishes'],
    families: {
      menu: { label: 'Menu & Items', color: '#b45309' },
      ordering: { label: 'Ordering', color: '#dc2626' },
      reservation: { label: 'Reservations', color: '#2d6a4f' },
      kitchen: { label: 'Kitchen & Prep', color: '#b45309' },
      social_proof: { label: 'Reviews & Social', color: '#be185d' },
      info: { label: 'Restaurant Info', color: '#7a7a70' },
    },
    blocks: [
      { id: 'menu_card', family: 'menu', label: 'Menu Item Card', stage: 'discovery', desc: 'Food item with dietary icons, spice level, allergen tags, portion options', intents: ['menu', 'food', 'dishes', 'what do you serve'], module: 'items', visualStyle: 'food gradient image, veg/non-veg dot, spice flame icons, portion toggle' },
      { id: 'menu_category', family: 'menu', label: 'Menu Category', stage: 'discovery', desc: 'Category section with emoji header, item count, browsable sub-items', intents: ['starters', 'mains', 'desserts', 'drinks', 'categories'], module: 'items', visualStyle: 'emoji + category name header, horizontal scroll preview, item count' },
      { id: 'customizer', family: 'ordering', label: 'Item Customizer', stage: 'showcase', desc: 'Build-your-own with toppings, sides, size, special instructions', intents: ['customize', 'add toppings', 'extra', 'special', 'modify'], module: null, visualStyle: 'checkbox groups for toppings, radio for size, textarea for instructions, running total' },
      { id: 'reservation', family: 'reservation', label: 'Table Reservation', stage: 'conversion', desc: 'Date/time picker with party size, seating preference, special occasion', intents: ['reserve', 'table', 'book a table', 'party of', 'seating'], module: null, visualStyle: 'date strip, time grid, party size stepper, seating preference pills (indoor/outdoor/bar)' },
      { id: 'order_status', family: 'ordering', label: 'Live Order Status', stage: 'followup', desc: 'Real-time kitchen status — ordered, preparing, ready, served', intents: ['order status', 'where is my food', 'how long', 'ready'], module: null, visualStyle: 'horizontal step timeline with kitchen icons, ETA countdown, item checklist' },
      { id: 'chef_profile', family: 'info', label: 'Chef / Owner Profile', stage: 'social_proof', desc: 'Chef bio with signature dishes, awards, philosophy', intents: ['chef', 'owner', 'who cooks', 'about'], module: null, visualStyle: 'portrait image, award badges, signature dish thumbnails, philosophy quote' },
      { id: 'combo_meal', family: 'menu', label: 'Combo / Set Meal', stage: 'showcase', desc: 'Fixed-price meal combo with included items and savings', intents: ['combo', 'set meal', 'thali', 'value meal', 'deal'], module: 'items', visualStyle: 'stacked item list with included icons, total vs individual price, savings callout' },
      { id: 'dietary_filter', family: 'menu', label: 'Dietary Filter', stage: 'discovery', desc: 'Filter pills for veg, vegan, gluten-free, halal, nut-free', intents: ['vegetarian', 'vegan', 'gluten free', 'halal', 'allergies', 'dietary'], module: null, visualStyle: 'colorful toggle pills with dietary icons, active count indicator' },
      { id: 'food_review', family: 'social_proof', label: 'Food Reviews', stage: 'social_proof', desc: 'Reviews with dish photos, taste/service/ambiance ratings', intents: ['reviews', 'ratings', 'how is the food'], module: null, visualStyle: 'Zomato/Google-style aggregate, dish photo thumbnails in reviews, 3-axis rating' },
      { id: 'happy_hour', family: 'info', label: 'Happy Hour / Specials', stage: 'showcase', desc: 'Time-limited specials with countdown, available hours, featured items', intents: ['specials', 'happy hour', 'today\'s special', 'deal'], module: null, visualStyle: 'countdown timer header, featured item cards, available hours badge' },
      { id: 'delivery_info', family: 'info', label: 'Delivery & Pickup', stage: 'objection', desc: 'Delivery radius, minimum order, estimated time, pickup instructions', intents: ['delivery', 'pickup', 'takeaway', 'how long', 'minimum order'], module: null, visualStyle: 'delivery zone map, time estimate, min order callout, platform links (Swiggy/Zomato)' },
      { id: 'catering_quote', family: 'ordering', label: 'Catering Request', stage: 'conversion', desc: 'Event catering form with guest count, menu selection, budget range', intents: ['catering', 'event', 'party', 'bulk order', 'corporate lunch'], module: null, visualStyle: 'guest count stepper, menu type selector, budget range slider, date picker' },
    ],
    subVerticals: [
      { id: 'full_service_restaurant', name: 'Full-Service Restaurant', blocks: ['menu_card', 'menu_category', 'customizer', 'reservation', 'food_review', 'chef_profile', 'combo_meal', 'happy_hour', 'delivery_info'] },
      { id: 'casual_dining', name: 'Casual Dining', blocks: ['menu_card', 'menu_category', 'reservation', 'combo_meal', 'food_review', 'happy_hour', 'delivery_info'] },
      { id: 'qsr', name: 'Quick Service (QSR)', blocks: ['menu_card', 'menu_category', 'customizer', 'combo_meal', 'order_status', 'food_review', 'delivery_info'] },
      { id: 'beverage_cafe', name: 'Cafe / Beverage', blocks: ['menu_card', 'menu_category', 'customizer', 'food_review', 'happy_hour', 'delivery_info'] },
      { id: 'bakery_desserts', name: 'Bakery & Desserts', blocks: ['menu_card', 'menu_category', 'food_review', 'combo_meal', 'delivery_info', 'catering_quote'] },
      { id: 'cloud_kitchen', name: 'Cloud Kitchen', blocks: ['menu_card', 'menu_category', 'customizer', 'combo_meal', 'order_status', 'food_review', 'dietary_filter', 'delivery_info'] },
      { id: 'catering_events', name: 'Catering & Events', blocks: ['menu_card', 'menu_category', 'combo_meal', 'catering_quote', 'food_review', 'chef_profile'] },
      { id: 'bars_pubs', name: 'Bars, Pubs & Breweries', blocks: ['menu_card', 'menu_category', 'reservation', 'happy_hour', 'food_review'] },
      { id: 'street_food', name: 'Street Food & Mobile', blocks: ['menu_card', 'menu_category', 'combo_meal', 'food_review', 'delivery_info'] },
    ],
  },
  {
    id: 'personal_wellness',
    industryId: 'personal_wellness',
    name: 'Personal Care & Wellness',
    iconEmoji: '✨',
    accentColor: '#9333ea',
    status: 'planned',
    blockCount: 12,
    subVerticalCount: 8,
    uniquePatterns: ['service card with duration bar + gender indicator', 'stylist/therapist card with portfolio', 'membership tier comparison', 'before/after gallery', 'slot picker with staff preference'],
    families: {},
    blocks: [],
    subVerticals: [
      { id: 'hair_beauty', name: 'Hair & Beauty Salon', blocks: [] },
      { id: 'spa_massage', name: 'Spa & Massage', blocks: [] },
      { id: 'fitness_gym', name: 'Fitness & Gym', blocks: [] },
      { id: 'yoga_meditation', name: 'Yoga & Meditation', blocks: [] },
      { id: 'skin_aesthetic', name: 'Skin & Aesthetic Clinic', blocks: [] },
      { id: 'nail_studio', name: 'Nail & Lash Studio', blocks: [] },
      { id: 'tattoo_piercing', name: 'Tattoo & Piercing', blocks: [] },
      { id: 'weight_nutrition', name: 'Weight & Nutrition', blocks: [] },
    ],
  },
  {
    id: 'financial',
    industryId: 'financial_services',
    name: 'Financial Services',
    iconEmoji: '🏦',
    accentColor: '#1e40af',
    status: 'planned',
    blockCount: 10,
    subVerticalCount: 8,
    uniquePatterns: ['product comparison table (loans/plans)', 'EMI calculator with slider', 'document checklist with upload status', 'KYC verification flow', 'policy summary card'],
    families: {},
    blocks: [],
    subVerticals: [
      { id: 'retail_banking', name: 'Retail Banking', blocks: [] },
      { id: 'insurance_brokerage', name: 'Insurance Brokerage', blocks: [] },
      { id: 'wealth_management', name: 'Wealth Management', blocks: [] },
      { id: 'accounting_tax', name: 'Accounting & Tax', blocks: [] },
      { id: 'consumer_lending', name: 'Consumer Lending', blocks: [] },
      { id: 'alternative_lending', name: 'Alternative Lending', blocks: [] },
      { id: 'investment_trading', name: 'Investment & Trading', blocks: [] },
      { id: 'fintech', name: 'Fintech', blocks: [] },
    ],
  },
  {
    id: 'automotive',
    industryId: 'automotive_mobility',
    name: 'Automotive & Mobility',
    iconEmoji: '🚗',
    accentColor: '#334155',
    status: 'planned',
    blockCount: 10,
    subVerticalCount: 7,
    uniquePatterns: ['vehicle card with spec grid (mileage/engine/transmission)', 'service estimate builder', 'service history timeline', 'test drive scheduler', 'tire/part finder with fitment check'],
    families: {},
    blocks: [],
    subVerticals: [
      { id: 'vehicle_sales_new', name: 'New Vehicle Sales', blocks: [] },
      { id: 'vehicle_sales_used', name: 'Used Vehicle Sales', blocks: [] },
      { id: 'vehicle_maintenance', name: 'Service & Repair', blocks: [] },
      { id: 'car_wash', name: 'Car Wash & Detailing', blocks: [] },
      { id: 'auto_parts', name: 'Auto Parts & Accessories', blocks: [] },
      { id: 'vehicle_rental', name: 'Vehicle Rental', blocks: [] },
      { id: 'ev_infrastructure', name: 'EV & Charging', blocks: [] },
    ],
  },
  {
    id: 'home_property',
    industryId: 'home_property',
    name: 'Home & Property Services',
    iconEmoji: '🔧',
    accentColor: '#92400e',
    status: 'planned',
    blockCount: 8,
    subVerticalCount: 6,
    uniquePatterns: ['service request form with photo upload', 'estimate/quote builder with line items', 'technician card with rating + ETA', 'job progress tracker', 'before/after project gallery'],
    families: {},
    blocks: [],
    subVerticals: [
      { id: 'plumbing_electrical', name: 'Plumbing & Electrical', blocks: [] },
      { id: 'appliance_repair', name: 'Appliance Repair', blocks: [] },
      { id: 'painting_renovation', name: 'Painting & Renovation', blocks: [] },
      { id: 'cleaning_housekeeping', name: 'Cleaning & Housekeeping', blocks: [] },
      { id: 'pest_control', name: 'Pest Control', blocks: [] },
      { id: 'landscaping_gardening', name: 'Landscaping & Gardening', blocks: [] },
    ],
  },
  {
    id: 'travel_transport',
    industryId: 'travel_transport',
    name: 'Travel & Transport',
    iconEmoji: '✈️',
    accentColor: '#0369a1',
    status: 'planned',
    blockCount: 8,
    subVerticalCount: 5,
    uniquePatterns: ['trip package card with itinerary preview', 'fare comparison table', 'visa requirement checker', 'live tracking map', 'traveler document checklist'],
    families: {},
    blocks: [],
    subVerticals: [
      { id: 'travel_agency', name: 'Travel Agency & Tours', blocks: [] },
      { id: 'visa_immigration', name: 'Visa & Immigration', blocks: [] },
      { id: 'taxi_ride', name: 'Taxi & Ride Services', blocks: [] },
      { id: 'logistics_courier', name: 'Logistics & Courier', blocks: [] },
      { id: 'luxury_adventure', name: 'Luxury & Adventure', blocks: [] },
    ],
  },
  {
    id: 'events_entertainment',
    industryId: 'events_entertainment',
    name: 'Events & Entertainment',
    iconEmoji: '🎉',
    accentColor: '#7c3aed',
    status: 'planned',
    blockCount: 8,
    subVerticalCount: 5,
    uniquePatterns: ['event package builder with customizable add-ons', 'vendor card with portfolio thumbnails', 'timeline/agenda view', 'ticket/RSVP with QR code', 'mood board / theme selector'],
    families: {},
    blocks: [],
    subVerticals: [
      { id: 'event_planning', name: 'Event Planning', blocks: [] },
      { id: 'wedding_private', name: 'Wedding & Private Events', blocks: [] },
      { id: 'photography_video', name: 'Photography & Video', blocks: [] },
      { id: 'live_entertainment', name: 'Live Entertainment', blocks: [] },
      { id: 'cinemas_theaters', name: 'Cinemas & Theaters', blocks: [] },
    ],
  },
  {
    id: 'business_professional',
    industryId: 'business_professional',
    name: 'Business & Professional',
    iconEmoji: '💼',
    accentColor: '#4338ca',
    status: 'planned',
    blockCount: 8,
    subVerticalCount: 5,
    uniquePatterns: ['consultation booking with case type selector', 'project portfolio with outcome metrics', 'retainer/pricing tiers', 'case study card with ROI metrics', 'team expertise matrix'],
    families: {},
    blocks: [],
    subVerticals: [
      { id: 'real_estate', name: 'Real Estate Services', blocks: [] },
      { id: 'legal_services', name: 'Legal Services', blocks: [] },
      { id: 'consulting_advisory', name: 'Consulting & Advisory', blocks: [] },
      { id: 'marketing_advertising', name: 'Marketing & Advertising', blocks: [] },
      { id: 'software_it', name: 'Software & IT Services', blocks: [] },
    ],
  },
  {
    id: 'food_supply',
    industryId: 'food_supply',
    name: 'Food Supply & Distribution',
    iconEmoji: '🥬',
    accentColor: '#15803d',
    status: 'planned',
    blockCount: 6,
    subVerticalCount: 4,
    uniquePatterns: ['wholesale product card with MOQ + bulk pricing tiers', 'freshness/harvest date indicator', 'subscription box builder', 'delivery route/schedule display'],
    families: {},
    blocks: [],
    subVerticals: [
      { id: 'grocery_wholesale', name: 'Grocery Wholesale', blocks: [] },
      { id: 'organic_farm', name: 'Organic & Farm Direct', blocks: [] },
      { id: 'meat_seafood', name: 'Meat & Seafood Supply', blocks: [] },
      { id: 'specialty_imported', name: 'Specialty & Imported Foods', blocks: [] },
    ],
  },
  {
    id: 'public_nonprofit',
    industryId: 'public_nonprofit',
    name: 'Public & Non-Profit',
    iconEmoji: '🏛️',
    accentColor: '#475569',
    status: 'planned',
    blockCount: 6,
    subVerticalCount: 3,
    uniquePatterns: ['donation card with impact metrics', 'service directory with eligibility checker', 'event/program calendar', 'volunteer signup form'],
    families: {},
    blocks: [],
    subVerticals: [
      { id: 'ngo_nonprofit', name: 'NGOs & Non-Profits', blocks: [] },
      { id: 'government', name: 'Government Services', blocks: [] },
      { id: 'community_association', name: 'Community Associations', blocks: [] },
    ],
  },
];

export function getVerticalManifest() {
  return VERTICAL_MANIFEST;
}

export function getPlannedVerticals() {
  return VERTICAL_MANIFEST.filter(v => v.status === 'planned');
}

export function getActiveVerticals() {
  return VERTICAL_MANIFEST.filter(v => v.status === 'done' || v.status === 'in_progress');
}

export function getTotalBlockCount() {
  return VERTICAL_MANIFEST.reduce((sum, v) => sum + v.blockCount, 0) + 6;
}

export function getTotalSubVerticalCount() {
  return VERTICAL_MANIFEST.reduce((sum, v) => sum + v.subVerticalCount, 0);
}
